### ISSUE TITLE
Can an FTA agent run in the Docker image?

### ISSUE THREAD

**Issue by Liturgist** [WAdev0/agent-docker-kit#2]

**Comment by fmossott** [comment]
Currently it's not supported, and even if it should run in docker it's hard to move in an external volumes all files that need to be persisted (e.g. symphony and .msg files)
We are working to simplify that in order to have master and DWC running in docker containers in the next future.
Currently we are not planning to have official containers for FTAs because in our opinion Dynamic Agents can better leverage Docker/Kubernetes environment.
Feel free to open an RFE if you have a business need to run FTAs in docker containers.

**Comment by Liturgist** [comment]
Thanks for your quick reply.
